#!/bin/bash
# Finds all mutation-finite quivers of a certain size.
# See README for usage information.

function ext {
	size="$1"
	shift
	cmd="$@"
	if [ "$size" -eq 2 ];
	then
		tmp="echo \"{ { 0 } }\" | qvfex | qvtrim -e ${cmd}"
		echo $tmp
	else
		tmp="| qvfex | qvtrim -e  ${cmd}"
		s=$(($size-1))
		ext ${s} $tmp
	fi
}

size="$1"
opt="$2"
tmp=""
if [ "${size}" -eq 2 ];
then
	tmp="echo \"{ { 0 } }\" | qvfex | qvtrim -e"
else
	tmp=`ext ${size} ""`
fi
cmd="${tmp} ${opt}"
eval ${cmd}

